# Generated by Django 4.2.4 on 2023-11-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_discountedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeEnergyMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('rechargeenergymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.rechargeenergymixin')),
                ('name', models.CharField(max_length=100)),
                ('hero_title', models.CharField(max_length=100)),
            ],
            bases=('main_app.rechargeenergymixin',),
        ),
        migrations.CreateModel(
            name='FlashHero',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.hero',),
        ),
        migrations.CreateModel(
            name='SpiderHero',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.hero',),
        ),
    ]
