"""Modify Recipe Table

Revision ID: 09f65a8fadbd
Revises: ff306c44e155
Create Date: 2023-11-16 13:35:50.330799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f65a8fadbd'
down_revision: Union[str, None] = 'ff306c44e155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
