"""Modify Recipe Table

Revision ID: f42877ba3baf
Revises: 4983f82a6d3b
Create Date: 2023-11-16 13:09:39.410474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42877ba3baf'
down_revision: Union[str, None] = '4983f82a6d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'chef_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'chef_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
