# Generated by Django 5.1.2 on 2024-10-24 10:06

import django.core.validators
import tastyrecipes.userprofile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Nickname must be at least 2 chars long!')], verbose_name='Nickname')),
                ('firstname', models.CharField(max_length=30, validators=[tastyrecipes.userprofile.validators.NameValidator()], verbose_name='First Name')),
                ('lastname', models.CharField(max_length=30, validators=[tastyrecipes.userprofile.validators.NameValidator()], verbose_name='Last Name')),
                ('chef', models.BooleanField(default=False, verbose_name='Chef')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
            ],
        ),
    ]
