# Generated by Django 4.2.4 on 2023-10-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main_app', '0005_shoe_delete_product'), ('main_app', '0006_uniquebrands')]

    dependencies = [
        ('main_app', '0004_auto_20231019_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.CreateModel(
            name='UniqueBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
