# Generated by Django 4.2.4 on 2023-10-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
