# Generated by Django 4.2.4 on 2023-10-21 14:18

from django.db import migrations


def add_price(apps, schema_editor):
    Smartphone = apps.get_model("main_app", "Smartphone")
    all_phones = Smartphone.objects.all()

    for phone in all_phones:
        phone.price = len(phone.brand) * 120
        phone.save()

# set categories function and a third one that combines them then its reverse function
# check props drilling concept

def reverse_add_price(apps, schema_editor):
    Smartphone = apps.get_model("main_app", "Smartphone")
    all_phones = Smartphone.objects.all()

    for phone in all_phones:
        phone.price = 0.00
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_smartphone'),
    ]

    operations = [migrations.RunPython(
        add_price, reverse_code=reverse_add_price
    )
    ]
