# Generated by Django 4.2.4 on 2023-10-21 14:23

from django.db import migrations


def add_category(apps, schema_editor):
    Smartphone = apps.get_model("main_app", "Smartphone")
    all_phones = Smartphone.objects.all()

    for phone in all_phones:
        if phone.price >= 750:
            phone.category = "Expensive"
        else:
            phone.category = "Cheap"

        phone.save()


def reverse_add_category(apps, schema_editor):
    Smartphone = apps.get_model("main_app", "Smartphone")
    all_phones = Smartphone.objects.all()

    for phone in all_phones:
        phone.category = "empty"

        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20231021_1718'),
    ]

    operations = [migrations.RunPython(
        add_category, reverse_code=reverse_add_category
    )
    ]
