# Generated by Django 4.2.4 on 2023-10-22 09:20

from datetime import timedelta

from django.db import migrations


def modify_delivery_warranty(apps, schema_editor):
    Order = apps.get_model("main_app", "Order")

    all_orders = Order.objects.all()

    for order in all_orders:
        if order.status == "Pending":
            order.delivery = order.order_date + timedelta(days=3)
        elif order.status == "Completed":
            order.warranty = "24 months"
        order.save()

    Order.objects.filter(status="Cancelled").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_order_status'),
    ]

    operations = [migrations.RunPython(
        modify_delivery_warranty)
    ]
