# Generated by Django 5.1.2 on 2024-10-25 12:30

import django.core.validators
import myplantapp.userprofile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Username')),
                ('first_name', models.CharField(max_length=20, validators=[myplantapp.userprofile.validators.UserNameValidator()], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, validators=[myplantapp.userprofile.validators.UserNameValidator()], verbose_name='First Name')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
            ],
        ),
    ]
