# Generated by Django 5.1.2 on 2024-10-23 17:48

import django.core.validators
import django.db.models.deletion
import worldofspeed.userprofile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rally', 'Rally'), ('open-wheel', 'Open-wheel'), ('kart', 'Kart'), ('drag', 'Drag'), ('Other', 'Other')], max_length=10, verbose_name='Car')),
                ('model', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Model')),
                ('year', models.IntegerField(validators=[worldofspeed.userprofile.validators.CarYearValidator()], verbose_name='Year')),
                ('image_url', models.URLField(unique=True, verbose_name='Image URL')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Price')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
            ],
        ),
    ]
