# Generated by Django 5.1.2 on 2024-10-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='userprofile.profile'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('rally', 'Rally'), ('open-wheel', 'Open-wheel'), ('kart', 'Kart'), ('drag', 'Drag'), ('Other', 'Other')], max_length=10, verbose_name='Type'),
        ),
    ]
