# Generated by Django 4.2.4 on 2023-10-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_hotelroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelRoom',
        ),
    ]
