# Generated by Django 5.1.2 on 2024-10-25 12:55

import django.core.validators
import django.db.models.deletion
import myplantapp.plant.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Outdoor', 'Outdoor'), ('Indoor', 'Indoor Plants')], max_length=14, verbose_name='Type')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), myplantapp.plant.validators.PlantNameValidator()], verbose_name='Name')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='userprofile.profile')),
            ],
        ),
    ]
