# Generated by Django 5.1.2 on 2024-10-23 10:03

import django.core.validators
import fruitipedia.userprofile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='fruit_name',
            field=models.CharField(error_messages={'unique': 'This fruit name is already in use! Try a new one.'}, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.userprofile.validators.FruitNameValidator()]),
        ),
    ]
